### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by gauravlath07** [rasbt/datacollect#3]
EXTREMELY uselful code. But I couldnt get it to work because https://www.dreamteamfc.com/c/statistics/players/ALL/
is outdated.

**Comment by rasbt** [comment]
yeah, I haven't used the script for ~1 1/2 years and they probably changed their website/layout since then. But if you happen to update it, I'd welcome a PR

**Comment by gauravlath07** [comment]
You got a sick repository mate. 

I have just started data dev. And was wondering if you could suggest me some ways to web scrape javascript enabled pages. I know I should be googling this stuff…but I couldn’t get any of them to work. And the other links suggested javascript solutions which i don’t want to venture into.

Would really appreciate advice from a veteran :)

Cheers !

**Comment by rasbt** [comment]
To be honest, I don't have much experience with scraping data from javascript enabled pages -- I was usually aiming for the HTML/static stuff. (When I worked with JavaScript-enabled pages, they usually came with specific APIs, or the data was available through raw json). I heard dryscape is quite good though, have a look: https://github.com/niklasb/dryscrape

**Comment by rasbt** [comment]
I hope to find some time one day to update all of this, but for now, let me close this issue since there already seems to be a similar one here: #2
